//
//  HealthMetrics.swift
//  MindfulHealth
//
//  Data models for health metrics
//

import Foundation
import HealthKit

// MARK: - Health Metric Types
struct HealthMetric: Identifiable {
    let id = UUID()
    let type: MetricType
    let value: Double
    let unit: String
    let date: Date
    let isAnomalous: Bool // Flagged by AI as unusual
    
    enum MetricType: String, CaseIterable {
        case steps = "Steps"
        case sleepHours = "Sleep"
        case heartRate = "Heart Rate"
        case heartRateVariability = "HRV"
        case activeEnergy = "Active Calories"
        case restingHeartRate = "Resting HR"
        
        var icon: String {
            switch self {
            case .steps: return "figure.walk"
            case .sleepHours: return "bed.double.fill"
            case .heartRate: return "heart.fill"
            case .heartRateVariability: return "waveform.path.ecg"
            case .activeEnergy: return "flame.fill"
            case .restingHeartRate: return "heart.circle.fill"
            }
        }
        
        var color: (start: String, end: String) {
            switch self {
            case .steps: return ("#667eea", "#764ba2")
            case .sleepHours: return ("#4facfe", "#00f2fe")
            case .heartRate: return ("#fa709a", "#fee140")
            case .heartRateVariability: return ("#30cfd0", "#330867")
            case .activeEnergy: return ("#f857a6", "#ff5858")
            case .restingHeartRate: return ("#ffecd2", "#fcb69f")
            }
        }
    }
}

// MARK: - Health Summary (for dashboard)
struct HealthSummary {
    let date: Date
    let steps: Double?
    let sleepHours: Double?
    let avgHeartRate: Double?
    let hrv: Double?
    let activeCalories: Double?
    let restingHR: Double?
    
    // Computed properties for baseline comparisons
    var stepsDeviation: Double?
    var sleepDeviation: Double?
    var hrvDeviation: Double?
}

// MARK: - AI Insight (generated by on-device LLM)
struct AIInsight: Identifiable {
    let id = UUID()
    let title: String
    let message: String
    let priority: Priority
    let actionItems: [String]
    let timestamp: Date
    
    enum Priority {
        case high      // Red - Needs attention
        case medium    // Yellow - Worth noting
        case low       // Green - Positive insight
        
        var color: String {
            switch self {
            case .high: return "#ff6b6b"
            case .medium: return "#ffd93d"
            case .low: return "#6bcf7f"
            }
        }
    }
}

// MARK: - Device Availability
enum DeviceCapability {
    case phoneOnly          // Just iPhone (limited data)
    case phoneAndWatch      // Full data from Apple Watch
    
    var availableMetrics: [HealthMetric.MetricType] {
        switch self {
        case .phoneOnly:
            return [.steps, .sleepHours] // Basic tracking
        case .phoneAndWatch:
            return HealthMetric.MetricType.allCases // All metrics
        }
    }
}

// MARK: - Chat Message
struct ChatMessage: Identifiable {
    let id = UUID()
    let content: String
    let isUser: Bool
    let timestamp: Date
    let healthContext: [String: Any]? // Optional health data context
}
